"""Add role, quantity, category

Revision ID: 39fac11a4152
Revises: fa7eee709405
Create Date: 2025-09-19 03:21:11.741281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fac11a4152'
down_revision: Union[str, Sequence[str], None] = 'fa7eee709405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sweets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sweets', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('sweets', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_sweets_category'), table_name='sweets')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_sweets_category'), 'sweets', ['category'], unique=False)
    op.alter_column('sweets', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sweets', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('sweets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
