"""Add role column to users table

Revision ID: fa7eee709405
Revises: 2f691d747b37
Create Date: 2025-09-19 02:48:31.659212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7eee709405'
down_revision: Union[str, Sequence[str], None] = '2f691d747b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sweets', sa.Column('category', sa.String(), nullable=True))
    op.add_column('sweets', sa.Column('quantity', sa.Integer(), nullable=False))
    op.alter_column('sweets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sweets', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_sweets_category'), 'sweets', ['category'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_sweets_category'), table_name='sweets')
    op.alter_column('sweets', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sweets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sweets', 'quantity')
    op.drop_column('sweets', 'category')
    # ### end Alembic commands ###
